spring:
  application:
    name: config #服务应用名称
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/macro-su/config.git
          search-paths:
            - common-dev
            - dev
          username:
          password:
server:
  port: 6001 #服务端口