server:
  port: 6001 #服务端口
eureka:
  instance:
    instance-id: config-6001
    prefer-ip-address: true     #访问路径可以显示IP地址
spring:
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/macro-su/Demacia.git
          search-paths: /config/config-repo/dev #配置仓库路径
          username:
          password: