server:
  port: 6001 #服务端口
spring:
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/macro-su/config.git
          search-paths:
            - common-dev
            - dev
          username:
          password: